spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-secret.properties   # TODO: 파일 복사로 바꾸기

  datasource:
    url: jdbc:mysql://localhost:3306/short_kki?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000
  refresh-token-validity: 604800000

oauth2:
  provider:
    google-ios:
      client-id: ${GOOGLE_IOS_CLIENT_ID}
      redirect-uri: ${GOOGLE_IOS_REDIRECT_URI}
    google-android:
      client-id: ${GOOGLE_ANDROID_CLIENT_ID}
      redirect-uri: ${GOOGLE_ANDROID_REDIRECT_URI}
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri: ${NAVER_REDIRECT_URI}

google:
  credential:
    api-key: ${GOOGLE_GENAI_API_KEY}
  gemini:
    model-name: ${GEMINI_MODEL_NAME:gemini-3-flash-preview}