spring:
  config:
    activate:
      on-profile: local
    import: classpath:application-secret.properties

  datasource:
    url: jdbc:h2:mem:short_kki;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
    # url: jdbc:mysql://localhost:3306/short_kki?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  flyway:
    enabled: false

  h2:
    console:
      enabled: true

jwt:
  secret: local__dev_only__short-kki__jwt-secret__32chars_min
  access-token-validity: 3600000
  refresh-token-validity: 604800000

oauth2:
  provider:
    google-ios:
      client-id: local-google-ios-client-id
      redirect-uri: com.googleusercontent.apps.local://
    google-android:
      client-id: local-google-android-client-id
      redirect-uri: shortkki://oauth/google
    kakao:
      client-id: local-kakao-client-id
      client-secret: local-kakao-client-secret
      redirect-uri: http://localhost:3000/oauth/callback/kakao
    naver:
      client-id: local-naver-client-id
      client-secret: local-naver-client-secret
      redirect-uri: http://localhost:3000/oauth/callback/naver

aws:
  service:
    s3:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}