spring:
  config:
    activate:
      on-profile: local
    import: classpath:application-secret.properties

  datasource:
    url: jdbc:mysql://localhost:3306/short_kki?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
    defer-datasource-initialization: true

  elasticsearch:
    uris: http://localhost:9200

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
#      mode: never

  flyway:
    enabled: false

jwt:
  secret: local__dev_only__short-kki__jwt-secret__32chars_min
  access-token-validity: 86400000
  refresh-token-validity: 604800000

oauth2:
  provider:
    google-ios:
      client-id: local-google-ios-client-id
      redirect-uri: com.googleusercontent.apps.local://
    google-android:
      client-id: local-google-android-client-id
      redirect-uri: shortkki://oauth/google
    kakao:
      client-id: local-kakao-client-id
      client-secret: local-kakao-client-secret
      redirect-uri: http://localhost:3000/oauth/callback/kakao
    naver:
      client-id: local-naver-client-id
      client-secret: local-naver-client-secret
      redirect-uri: http://localhost:3000/oauth/callback/naver

aws:
  service:
    s3:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

google:
  credential:
    api-key: ${GOOGLE_GENAI_API_KEY:google-api-test-key}
  services:
    gemini:
      model-name: gemini-3-flash-preview

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    try-it-out-enabled: true
    filter: true

logging:
  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
    org.elasticsearch.client.RestClient: DEBUG

public-data:
  ingredient:
    enabled: true
    type: xml
    api-url: Grid_20150827000000000227_1
    url-template: "http://211.237.50.150:7080/openapi/%s/%s/%s/%d/%d"
    start-index: 1
    end-index: 1000
    api-key: ${INGREDIENT_API_KEY}
