name: CI

# 언제 실행할지
on:
  push:
    branches: [ "develop", "feature/**" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    # 1. MYSQL 서비스 실행
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE_NAME }}
          TZ: Asia/Seoul
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 2. 코드 가져오기
      - name: Checkout source code
        uses: actions/checkout@v4

      # 3. 자바 21 설치
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # 4. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5. 빌드 및 테스트 (여기가 핵심!)
      # application-dev.yml의 빈 변수들을 여기서 채워줍니다.
      - name: Build with Gradle
        # 스프링 부트에게 "dev 프로필 써라" 명령
        run: ./gradlew build -Dspring.profiles.active=dev
        env:
          # DB 연결 정보
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TZ: Asia/Seoul


          JWT_SECRET: ${{ secrets.JWT_SECRET }}

          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: "http://localhost:8080/login/oauth2/code/google"

          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
          KAKAO_REDIRECT_URI: "http://localhost:8080/login/oauth2/code/kakao"

          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          NAVER_REDIRECT_URI: "http://localhost:8080/login/oauth2/code/naver"